name: Metrics
on:
  schedule: 
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
     - name: Achievements
       uses: lowlighter/metrics@latest
       with:
         filename: achievements.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_achievements: yes
       # plugin_achievements_display: compact
         repositories_skipped: Jai-JAP/re-GTA
         
     - name: Others
       uses: lowlighter/metrics@latest
       with:
         filename: others.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: header
         plugin_activity: yes
         plugin_activity_load: 100
         plugin_activity_days: 7
         plugin_activity_visibility: public
         plugin_activity_filter: issue, pr, fork, public, member
         plugin_isocalendar: yes
         plugin_languages: yes
         plugin_languages_details: lines, bytes-size, percentage
         plugin_languages_sections: most-used
         plugin_stars: yes
         plugin_notable: yes
         plugin_notable_repositories: yes
         plugin_topics: yes
         plugin_topics_limit: 0
         plugin_topics_mode: icons
         plugin_lines: yes
         plugin_gists: yes
         repositories_skipped: Jai-JAP/re-GTA
         
