name: Metrics
on:
  schedule: 
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
     - name: Achievements
       uses: lowlighter/metrics@latest
       with:
         filename: achievements.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_achievements: yes
       # plugin_achievements_display: compact
       
     - name: Others
       uses: lowlighter/metrics@latest
       with:
         filename: others.svg
         plugin_activity: yes
         plugin_activity_load: 100
         plugin_activity_days: 7
         plugin_activity_visibility: public
         plugin_activity_filter: issue, pr, fork, star, public, member
         repositories_skipped: Jai-JAP/re-GTA
         
