name: Metrics
on:
  schedule: 
    - cron: "0 0 */2 * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     
     - name: Achievements
       uses: lowlighter/metrics@latest
       with:
         filename: achievements.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: header
         config_octicon: yes
         plugin_achievements: yes
  #       plugin_achievements_display: compact
         repositories_skipped: Jai-JAP/re-GTA, Jai-JAP/gh-stats, Jai-JAP/nodeunblocker

     - name: Overview
       uses: lowlighter/metrics@latest
       with:
         filename: overview.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: header
         config_octicon: yes
         plugin_isocalendar: yes
         plugin_languages: yes
         plugin_languages_details: lines, bytes-size, percentage
         plugin_languages_sections: most-used
         plugin_stars: yes
         plugin_notable: yes
         plugin_notable_repositories: yes
         plugin_topics: yes
         plugin_topics_limit: 0
         plugin_lines: yes
         plugin_traffic: yes
#         plugin_gists: yes
         repositories_skipped: Jai-JAP/re-GTA, Jai-JAP/gh-stats

         
